// Question content keyed by `${topicId}/${partId}`.
// Recall = self-test flashcards; MCQ = board-style vignette pool.

export type RecallQ = { id: number; question: string; answer: string };
export type MCQ = {
  id: number;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
};

// ── Retina · Part 1 · Viral & Necrotizing Retinitis (CMV retinitis · ARN · PORN)
// Source: Ryan's Retina, Section 4 (Inflammatory Disease/Uveitis), Ch. 82.
const RETINA_VIRAL_RECALL: RecallQ[] = [
  { id: 1, question: "What is the most common retinal finding in HIV/AIDS, and is it infectious?", answer: "Cotton-wool spots — noninfectious nerve fiber layer infarcts seen in 50–75% of AIDS patients. They are transient (ophthalmoscopically visible ~6–12 weeks) and require no treatment. AIDS must be considered in the differential of cotton-wool spots occurring without hypertension or diabetes." },
  { id: 2, question: "At what CD4 count does the risk of CMV retinitis markedly increase?", answer: "Below 50/µL. Screening is reasonable below CD4 50–100/µL. In the HAART era, some patients develop CMV retinitis at CD4 >100/µL because of incomplete restoration of the immune repertoire against CMV." },
  { id: 3, question: "Describe the classic fundus appearance of posterior-pole CMV retinitis.", answer: "Full-thickness white intraretinal necrosis and areas of infiltrate along the vascular arcades, with prominent retinal hemorrhages within the necrotic area or along its leading (advancing) edge — the hemorrhagic 'brushfire' border." },
  { id: 4, question: "How does peripheral CMV retinitis differ from posterior-pole disease?", answer: "Peripheral CMV is more granular and has a less intense white appearance, and may lack hemorrhage. Patients may report only floaters, with or without a visual field deficit." },
  { id: 5, question: "What is 'smoldering' CMV retinitis?", answer: "A low grade of retinitis border activity associated with slow progression. It is difficult to recognize without prior wide-angle fundus photographs, which are more sensitive than indirect ophthalmoscopy for detecting progression." },
  { id: 6, question: "What characterizes reactivation of CMV retinitis?", answer: "Reopacification of the border of a previously healed lesion, followed by advancement of the leading edge." },
  { id: 7, question: "Does CMV retinitis usually produce heavy vitritis, and why does that matter for the differential?", answer: "No — in the immunosuppressed host CMV shows minimal inflammatory cells and little vitritis; choroidal involvement is also rare. Prominent vitritis with occlusive vasculitis should raise suspicion for acute retinal necrosis instead." },
  { id: 8, question: "What CNS association does CMV retinitis carry, and how does lesion location affect it?", answer: "CMV encephalitis. The risk is much higher when the retinitis involves the peripapillary region (up to 75% of peripapillary cases had encephalitis; relative risk ~13% for peripapillary vs 9.5% overall)." },
  { id: 9, question: "Name the four FDA-approved drugs for CMV retinitis.", answer: "Ganciclovir, valganciclovir, cidofovir, and foscarnet. (Fomivirsen was approved but is no longer available.)" },
  { id: 10, question: "Why is ganciclovir far more active against CMV than acyclovir, and what enzyme activates it?", answer: "CMV lacks a viral thymidine kinase. Ganciclovir is monophosphorylated by the CMV UL97 phosphotransferase and then converted to its active triphosphate, which inhibits viral DNA elongation. It is phosphorylated much more efficiently than acyclovir, accounting for its greater anti-CMV activity." },
  { id: 11, question: "What is the major dose-limiting toxicity of systemic ganciclovir, and what worsens it?", answer: "Granulocytopenia (neutropenia), occurring in up to one-third of patients; it is exacerbated by concurrent zidovudine (AZT). It is generally reversible, and G-CSF/GM-CSF can help." },
  { id: 12, question: "What is valganciclovir and its key pharmacologic advantage?", answer: "The valine ester (oral prodrug) of ganciclovir. The ester greatly enhances gut absorption — bioavailability ~60% vs ~6% for oral ganciclovir — giving plasma ganciclovir levels comparable to IV dosing. Typical dosing is 900 mg twice daily for induction and 900 mg daily for maintenance; diarrhea is the most common adverse effect." },
  { id: 13, question: "How does foscarnet's mechanism differ from ganciclovir's?", answer: "Foscarnet is a pyrophosphate analog that directly inhibits the viral DNA polymerase by preventing pyrophosphate exchange. It does NOT require phosphorylation or activation by viral or cellular enzymes." },
  { id: 14, question: "What are the principal toxicities of foscarnet?", answer: "Nephrotoxicity (dose-limiting; requires saline hydration and dose adjustment for renal function) and electrolyte disturbance — especially symptomatic hypocalcemia, which can cause arrhythmias and seizures and is worsened by concurrent IV pentamidine. Neutropenia is less common than with ganciclovir (14% vs 34%)." },
  { id: 15, question: "In the Foscarnet–Ganciclovir CMV Retinitis Trial, what surprising difference emerged?", answer: "Both drugs controlled the retinitis equally, but foscarnet conferred a survival advantage (median ~12.6 vs 8.5 months), attributed in part to foscarnet's direct anti-HIV activity. However, foscarnet was less well tolerated." },
  { id: 16, question: "What is cidofovir, its dosing advantage, and its characteristic ocular toxicities?", answer: "A nucleotide analog (HPMPC) with a long duration of action — IV weekly induction then biweekly, or intravitreal every 5–6 weeks. It characteristically causes iritis (up to ~50%, reduced to ~18% with oral probenecid) and ocular hypotony from ciliary body atrophy. Systemic nephrotoxicity (proximal tubule) requires probenecid plus saline hydration." },
  { id: 17, question: "Which CMV genes mediate resistance to the anti-CMV drugs?", answer: "UL97 mutations → low-level ganciclovir resistance; UL97 + UL54 mutations → high-level ganciclovir resistance; UL54 (DNA polymerase) mutations → foscarnet and cidofovir resistance. Ganciclovir-resistant strains (UL97) often remain foscarnet-sensitive." },
  { id: 18, question: "What is the mechanism of fomivirsen?", answer: "An antisense oligonucleotide complementary to CMV mRNA of the major immediate-early region (IE2), inhibiting production of essential viral proteins. It does NOT target the DNA polymerase. Given intravitreally; no longer available." },
  { id: 19, question: "Why must a ganciclovir intraocular device (implant) be combined with systemic therapy?", answer: "Local therapy does not treat systemic CMV, so implant-alone carries a higher risk of contralateral CMV retinitis and extraocular CMV disease; oral valganciclovir is added. Implants also carry an early (first 2 months) retinal detachment risk and ~1% endophthalmitis risk." },
  { id: 20, question: "What is the mechanism and typical timing of retinal detachment in CMV retinitis?", answer: "Rhegmatogenous RD from breaks in atrophic/necrotic retina (active or healed), median time ~18 months. Risk factors: extent of peripheral disease, retinitis activity, and involvement of anterior retina near the vitreous base. HAART reduced RD incidence by ~60%." },
  { id: 21, question: "What is immune recovery uveitis (IRU)?", answer: "An intraocular inflammatory response (iritis, vitritis, macular edema, epiretinal membrane, cataract) in eyes with healed CMV retinitis after immune reconstitution on HAART. Larger retinitis surface area and prior cidofovir use increase risk. It is treated with periocular or intravitreal corticosteroids." },
  { id: 22, question: "Contrast the causative organism and host immune status of CMV retinitis, ARN, and PORN.", answer: "CMV retinitis: cytomegalovirus, very low CD4 (<50/µL). ARN: usually VZV (HSV possible), relatively preserved immunity (CD4 usually >60/µL). PORN: nearly always VZV, profound immunosuppression (CD4 <50/µL)." },
  { id: 23, question: "Describe the clinical picture of acute retinal necrosis (ARN).", answer: "A fulminant panuveitis with confluent, well-demarcated peripheral retinitis (deep retinal whitening, minimal hemorrhage, rapid progression), prominent anterior uveitis, occlusive retinal and choroidal vasculitis, vitritis, and papillitis. Retinal detachment with multiple breaks in the necrotic retina is a common sequela, often with PVR." },
  { id: 24, question: "How does PORN differ clinically from ARN?", answer: "Progressive outer retinal necrosis shows early patchy, multifocal DEEP OUTER retinal lesions with characteristic perivascular clearing, and notably ABSENT vascular inflammation with minimal or no vitritis (versus ARN's prominent vasculitis and vitritis). It progresses extremely rapidly, with severe vision loss and retinal detachment in up to 70%." },
  { id: 25, question: "Outline treatment principles for ARN and PORN.", answer: "ARN: prompt IV acyclovir (10 mg/kg q8h) followed by oral maintenance (valacyclovir/famciclovir/acyclovir); consider prophylactic barrier laser; early combination IV antivirals can arrest disease. PORN: high-dose combination therapy (IV plus intravitreal ganciclovir and foscarnet, ± oral valganciclovir) because IV acyclovir monotherapy gives poor results (NLP in ~67%); ART is important and laser demarcation may reduce detachment." },
];

const RETINA_VIRAL_MCQ: MCQ[] = [
  { id: 1, question: "A 32-year-old man with AIDS (CD4 12/µL) reports floaters and a peripheral field defect. Fundus shows a granular white area of retinal necrosis along a vascular arcade with hemorrhage at its advancing border. Most likely diagnosis?", options: ["Toxoplasmic retinochoroiditis", "Cytomegalovirus retinitis", "Acute retinal necrosis", "Cotton-wool spots"], correct: 1, explanation: "Full-thickness white retinal necrosis with hemorrhage at the leading edge in a patient with CD4 <50/µL is classic CMV retinitis. Toxoplasmosis shows a focal lesion with overlying dense vitritis ('headlight in the fog'); ARN has prominent vitritis and occlusive vasculitis and occurs at higher CD4 counts." },
  { id: 2, question: "Below which CD4 count does the risk of CMV retinitis markedly increase?", options: ["200/µL", "100/µL", "50/µL", "350/µL"], correct: 2, explanation: "The risk rises sharply below 50/µL. Screening is reasonable below CD4 50–100/µL." },
  { id: 3, question: "A previously healed CMV lesion border becomes re-opacified and begins to advance. This represents:", options: ["Immune recovery uveitis", "Reactivation of CMV retinitis", "Progressive outer retinal necrosis", "Serous macular exudation"], correct: 1, explanation: "Reactivation is defined by reopacification of the healed border followed by advancement of the leading edge." },
  { id: 4, question: "Which feature most argues AGAINST CMV retinitis and FOR acute retinal necrosis?", options: ["Full-thickness necrosis", "Prominent occlusive vasculitis and dense vitritis", "Retinal hemorrhage", "Peripheral location"], correct: 1, explanation: "In the immunosuppressed host CMV shows minimal vitritis; ARN features a fulminant panuveitis with occlusive vasculitis and prominent vitritis." },
  { id: 5, question: "Ganciclovir is much more active against CMV than acyclovir because:", options: ["It directly inhibits DNA polymerase without phosphorylation", "It is phosphorylated by the CMV UL97 phosphotransferase (CMV lacks a viral thymidine kinase)", "It targets IE2 messenger RNA", "It is a pyrophosphate analog"], correct: 1, explanation: "CMV lacks a thymidine kinase; the UL97 kinase performs the first phosphorylation of ganciclovir. Option A describes foscarnet, C describes fomivirsen, and D describes foscarnet." },
  { id: 6, question: "The major dose-limiting toxicity of systemic ganciclovir is:", options: ["Nephrotoxicity", "Granulocytopenia (neutropenia)", "Hypocalcemia", "Iritis"], correct: 1, explanation: "Granulocytopenia occurs in up to one-third of patients and is worsened by concurrent zidovudine (AZT)." },
  { id: 7, question: "Which drug is a pyrophosphate analog that inhibits viral DNA polymerase without requiring intracellular phosphorylation?", options: ["Ganciclovir", "Valganciclovir", "Foscarnet", "Cidofovir"], correct: 2, explanation: "Foscarnet directly blocks pyrophosphate exchange at the viral DNA polymerase and needs no activation by viral or cellular enzymes." },
  { id: 8, question: "A patient on IV foscarnet develops perioral tingling, carpopedal spasm, and a seizure. The most likely cause is:", options: ["Hypocalcemia", "Hyperkalemia", "Neutropenia", "Lactic acidosis"], correct: 0, explanation: "Foscarnet chelates divalent cations, causing symptomatic hypocalcemia (arrhythmias, seizures); the risk is increased by concurrent IV pentamidine." },
  { id: 9, question: "Valganciclovir's principal advantage over oral ganciclovir is:", options: ["It is a different drug class", "Much higher oral bioavailability (~60% vs ~6%), giving IV-comparable levels", "It carries no risk of neutropenia", "It inhibits the DNA polymerase directly"], correct: 1, explanation: "The valine ester dramatically improves gut absorption; once absorbed it is cleaved to ganciclovir, so it shares ganciclovir's toxicity profile (including neutropenia)." },
  { id: 10, question: "Intravitreal or IV cidofovir characteristically causes which ocular side effects?", options: ["Iritis and ocular hypotony", "Cataract and angle-closure glaucoma", "Optic neuritis", "Band keratopathy"], correct: 0, explanation: "Cidofovir causes iritis (reduced from ~50% to ~18% with oral probenecid) and hypotony due to ciliary body atrophy." },
  { id: 11, question: "To reduce cidofovir nephrotoxicity, you administer:", options: ["Allopurinol", "Probenecid and IV saline hydration", "Mannitol", "Acetazolamide"], correct: 1, explanation: "Probenecid blocks proximal tubular uptake of cidofovir, and saline loading reduces nephrotoxicity." },
  { id: 12, question: "High-level ganciclovir resistance in CMV typically involves mutations in:", options: ["UL97 alone", "UL54 alone", "Both UL97 and UL54", "The thymidine kinase gene"], correct: 2, explanation: "UL97 alone → low-level ganciclovir resistance; UL97 + UL54 → high-level resistance; UL54 alone → foscarnet/cidofovir resistance. CMV has no thymidine kinase gene of the relevant type." },
  { id: 13, question: "A ganciclovir-resistant CMV strain caused by a UL97 mutation would be expected to:", options: ["Also be resistant to foscarnet", "Remain susceptible to foscarnet", "Respond only to acyclovir", "Be untreatable"], correct: 1, explanation: "Foscarnet resistance is mediated by UL54 (DNA polymerase) mutations, so UL97 ganciclovir-resistant strains usually remain foscarnet-sensitive." },
  { id: 14, question: "Fomivirsen exerts its anti-CMV effect by:", options: ["Inhibiting the DNA polymerase", "Antisense binding to CMV IE2 (immediate-early) mRNA", "Blocking the UL97 kinase", "Chelating pyrophosphate"], correct: 1, explanation: "Fomivirsen is an antisense oligonucleotide targeting the major immediate-early (IE2) mRNA, blocking essential viral protein production; it does not act on the DNA polymerase." },
  { id: 15, question: "Why is a ganciclovir intraocular device typically combined with systemic (oral valganciclovir) therapy?", options: ["To reduce cataract formation", "Because local therapy does not treat systemic CMV or protect the fellow eye", "To lower intraocular pressure", "To speed healing of the injection wound"], correct: 1, explanation: "The implant treats only the eye it is in; implant-alone raises the risk of contralateral CMV retinitis and extraocular CMV disease, so systemic therapy is added." },
  { id: 16, question: "Which is the main early ocular risk in the first 2 months after ganciclovir implant placement?", options: ["Endophthalmitis in 20%", "Rhegmatogenous retinal detachment", "Choroidal neovascularization", "Vitreous hemorrhage from the implant strut"], correct: 1, explanation: "Retinal detachment risk is substantially higher in the first 2 months after insertion; endophthalmitis risk is on the order of ~1%." },
  { id: 17, question: "Retinal detachment in CMV retinitis is best described as:", options: ["Tractional from fibrovascular proliferation", "Exudative from a choroidal leak", "Rhegmatogenous from breaks in necrotic/atrophic retina", "Serous from RPE dysfunction"], correct: 2, explanation: "Breaks form in atrophic necrotic retina (active or healed). Median time to detachment is ~18 months; HAART reduced the incidence by ~60%." },
  { id: 18, question: "Surgical repair of CMV-related rhegmatogenous retinal detachment most often uses:", options: ["Pneumatic retinopexy", "Scleral buckle alone", "Pars plana vitrectomy with silicone oil", "Laser demarcation alone"], correct: 2, explanation: "Because of multiple posterior breaks in fragile necrotic retina and frequent PVR, vitrectomy with silicone oil tamponade is typically required." },
  { id: 19, question: "A patient with previously healed CMV retinitis starts HAART; CD4 rises to 150. He now develops vitritis, macular edema, and an epiretinal membrane. The diagnosis is:", options: ["Reactivation of CMV", "Immune recovery uveitis", "New acute retinal necrosis", "Bacterial endophthalmitis"], correct: 1, explanation: "Immune reconstitution produces an inflammatory response to residual CMV antigen in healed lesions — immune recovery uveitis." },
  { id: 20, question: "First-line management of vision-threatening immune recovery uveitis is:", options: ["Systemic ganciclovir", "Periocular or intravitreal corticosteroids", "Intravitreal antibiotics", "Immediate vitrectomy"], correct: 1, explanation: "IRU is an inflammatory (not actively infectious) process in a healed lesion, managed with corticosteroids." },
  { id: 21, question: "In acute retinal necrosis (ARN), the most common causative virus is:", options: ["Cytomegalovirus", "Varicella-zoster virus", "Epstein–Barr virus", "HIV"], correct: 1, explanation: "ARN is most often caused by VZV; HSV can also cause it. CMV was once presumed but not confirmed." },
  { id: 22, question: "Which cluster of features is typical of ARN rather than CMV retinitis?", options: ["Minimal vitritis with hemorrhagic posterior lesions", "Prominent anterior uveitis, occlusive vasculitis, vitritis, and papillitis", "Deep outer-retinal lesions without any vasculitis", "Isolated cotton-wool spots"], correct: 1, explanation: "ARN is a fulminant panuveitis; CMV in the immunosuppressed is comparatively quiet, and PORN lacks vasculitis/vitritis." },
  { id: 23, question: "Preferred initial therapy for acute retinal necrosis is:", options: ["Oral doxycycline", "IV acyclovir (e.g., 10 mg/kg q8h) followed by oral antiviral maintenance", "Intravitreal antibiotics", "Systemic corticosteroids alone"], correct: 1, explanation: "Prompt IV acyclovir, then oral valacyclovir/famciclovir/acyclovir maintenance; prophylactic barrier laser is often considered. Steroids are adjunctive and avoided in advanced HIV immunosuppression." },
  { id: 24, question: "A frequent and serious sequela of acute retinal necrosis is:", options: ["Rhegmatogenous retinal detachment with multiple peripheral breaks and PVR", "Central retinal artery occlusion", "Anterior ischemic optic neuropathy", "Bacterial corneal ulcer"], correct: 0, explanation: "Retinal detachment develops in a large fraction of ARN eyes, with multiple breaks in necrotic retina and frequent proliferative vitreoretinopathy." },
  { id: 25, question: "Progressive outer retinal necrosis (PORN) is nearly always caused by:", options: ["HSV-1", "Varicella-zoster virus", "Cytomegalovirus", "Toxoplasma gondii"], correct: 1, explanation: "PORN is a herpetic retinitis variant nearly always caused by VZV, often with associated dermatomal zoster." },
  { id: 26, question: "Which finding best distinguishes PORN from ARN?", options: ["Prominent vitritis and occlusive vasculitis", "Deep multifocal outer-retinal opacification with perivascular clearing and minimal/absent vitritis", "Hemorrhage at the leading edge", "A requirement for high CD4 counts"], correct: 1, explanation: "PORN characteristically has deep outer retinal lesions with perivascular clearing and little to no inflammation, unlike the vasculitis and vitritis of ARN." },
  { id: 27, question: "PORN characteristically occurs in patients with:", options: ["CD4 > 200/µL", "Profound immunosuppression, CD4 < 50/µL", "Normal immune function", "Isolated neutropenia"], correct: 1, explanation: "PORN occurs in profoundly immunosuppressed patients (CD4 <50/µL), whereas ARN tends to occur at relatively higher CD4 counts (>60/µL)." },
  { id: 28, question: "Why does IV acyclovir monotherapy give poor visual outcomes in PORN?", options: ["It cannot cross the blood–retina barrier", "Extremely rapid necrosis plus frequent acyclovir resistance (often on prior acyclovir prophylaxis) — NLP in ~67%", "It is directly retinotoxic", "VZV is always intrinsically acyclovir-resistant"], correct: 1, explanation: "Engström et al. reported no light perception in 67% of eyes within 4 weeks on IV acyclovir alone, attributed to fulminant progression and acyclovir resistance." },
  { id: 29, question: "The current preferred approach for PORN is:", options: ["IV acyclovir alone", "Combination IV plus intravitreal antivirals (ganciclovir + foscarnet) with ART, ± laser demarcation", "Observation", "Corticosteroids alone"], correct: 1, explanation: "Combination IV and intravitreal ganciclovir/foscarnet with antiretroviral therapy improved outcomes (e.g., 20/80 or better in ~45%); laser demarcation may reduce detachment." },
  { id: 30, question: "Cotton-wool spots in an HIV patient without hypertension or diabetes:", options: ["Require urgent antiviral therapy", "Are noninfectious nerve fiber layer infarcts that are transient and need no treatment", "Indicate active CMV retinitis", "Are pathognomonic for ARN"], correct: 1, explanation: "Cotton-wool spots are the most common retinal finding in HIV (50–75%), are noninfectious NFL infarcts that resolve over 6–12 weeks, and need no treatment — though AIDS should be considered in the differential." },
];

// ── Cornea · Part 1 · Basic Science (moved from the part page; unchanged content)
const CORNEA_BASIC_RECALL: RecallQ[] = [
  { id: 1, question: "Why is the cornea transparent?", answer: "Collagen fibrils in the stroma are homogeneous in diameter and aligned at a constant spacing shorter than the wavelength of visible light — this causes destructive interference of scattered light, allowing transmission. Avascularity also prevents light scattering from red blood cells." },
  { id: 2, question: "What are the 5 layers of the cornea from anterior to posterior?", answer: "Epithelium → Bowman layer → Stroma → Descemet membrane → Endothelium. (Mnemonic: Every Bad Student Deserves Education)" },
  { id: 3, question: "What fraction of the eye's total refractive power does the cornea contribute?", answer: "More than two-thirds (~67%) of total refractive power. The lens accounts for the remaining ~33%." },
  { id: 4, question: "Where do corneal epithelial stem cells reside and what is the XYZ model?", answer: "Limbal stem cells reside in the basal layer at the palisades of Vogt. XYZ model: X = basal cell proliferation, Y = centripetal migration of transient amplifying cells, Z = desquamation. Z = X + Y must be maintained for homeostasis." },
  { id: 5, question: "How does the corneal endothelium maintain stromal transparency?", answer: "Via active fluid pumping (Na⁺/K⁺-ATPase and bicarbonate transport) that counteracts osmotic imbibition of water into the stroma. Failure causes stromal swelling → collagen fibril disruption → opacity and bullous keratopathy." },
  { id: 6, question: "What nerve supplies corneal sensation and what happens when it is damaged?", answer: "Ophthalmic division of the trigeminal nerve (CN V1) via long ciliary nerves. Damage causes neurotrophic keratopathy — painless persistent epithelial defects that fail to heal due to loss of trophic neuropeptides (substance P, IGF-1) and reduced blink reflex." },
  { id: 7, question: "What are the 3 essential functions of the tear film?", answer: "Lubrication (prevents mechanical damage from blinking), Protection (antimicrobial proteins: lysozyme, lactoferrin, IgA), and Refraction (provides the first and smoothest refracting surface of the eye — irregularities cause visual distortion)." },
  { id: 8, question: "What is the primary structural component of the corneal stroma and what percentage of corneal dry weight is it?", answer: "Type I collagen, constituting more than 70% of corneal dry weight. Proteoglycans (keratan sulfate, dermatan sulfate) fill the spaces between fibrils and regulate fibril diameter and spacing — critical for transparency." },
  { id: 9, question: "What is the physiologic role of the Bowman layer?", answer: "Its role remains unclear — many mammals lack a Bowman layer yet have normal corneal epithelial structure. It does NOT regenerate after injury. It may provide mechanical resistance and act as a barrier to epithelial downgrowth." },
  { id: 10, question: "Why can the cornea survive without blood vessels?", answer: "Oxygen arrives via the tear film (from atmosphere anteriorly) and from aqueous humor (posteriorly). Nutrients diffuse from limbal vessels at the periphery and from aqueous humor. Avascularity is essential — vessels would scatter light and destroy transparency." },
  { id: 11, question: "What are the key differences between the corneal and conjunctival epithelium?", answer: "Corneal epithelium is non-keratinized, stratified squamous (5–7 cell layers), with no goblet cells and tight junctions forming an effective barrier. Conjunctival epithelium is non-keratinizing stratified columnar/squamous with goblet cells (secrete MUC5AC) and is more permeable — used for drug absorption." },
  { id: 12, question: "What is the role of conjunctival goblet cells and what happens when they are lost?", answer: "Goblet cells secrete soluble mucin MUC5AC, which is the primary gel-forming mucin of the tear film. Loss (as in Stevens-Johnson syndrome, cicatricial pemphigoid, chemical burns) causes mucin-deficient dry eye with poor tear film stability despite adequate aqueous production." },
  { id: 13, question: "What is tear film osmolarity and why is it clinically important?", answer: "Normal tear osmolarity is ~305 mOsm/L. In dry eye disease, reduced aqueous production or increased evaporation leads to hyperosmolarity (>308 mOsm/L). Hyperosmolarity activates MAP kinase and NF-κB pathways → inflammatory cytokines → epithelial damage → perpetuates the vicious cycle of dry eye." },
  { id: 14, question: "What are the three layers of the tear film and what does each contribute?", answer: "Lipid layer (outermost, from meibomian glands): prevents evaporation, provides surface tension. Aqueous layer (middle, from lacrimal gland): contains electrolytes, growth factors, antibodies, oxygen. Mucin layer (innermost, from goblet cells): converts hydrophobic epithelial surface to hydrophilic, anchors tear film." },
  { id: 15, question: "What collagen types are found in the corneal stroma and what are their roles?", answer: "Type I collagen (major structural component, ~70% dry weight), Type V collagen (regulates fibril diameter — critical for transparency), Type VI collagen (anchors keratocytes to matrix). Type IV collagen is in Descemet membrane and basement membranes, not the stroma proper." },
  { id: 16, question: "What is the limbal stem cell niche and what structures comprise it?", answer: "The limbal stem cell niche is the microenvironment that maintains LSC quiescence and self-renewal. It includes: palisades of Vogt (interdigitations of limbal stroma), limbal epithelial crypts (proposed actual niche site), rich vascular and neural supply, and stromal mesenchymal cells that provide growth factors and ECM signals." },
  { id: 17, question: "What is the embryological origin of the corneal stroma, endothelium, and Descemet membrane?", answer: "All three derive from neural crest cells (neuroectoderm). The corneal epithelium derives from surface ectoderm. Understanding this is key: congenital anomalies like Peters anomaly, Axenfeld-Rieger syndrome, and congenital hereditary endothelial dystrophy (CHED) all involve neural crest cell dysfunction." },
  { id: 18, question: "How do keratocytes respond to corneal injury and what determines whether healing or scarring occurs?", answer: "Injured epithelium releases IL-1 and FasL → keratocyte apoptosis in wound zone → quiescent keratocytes activate into fibroblasts → if TGF-β is high (e.g., deep stromal wound), fibroblasts transdifferentiate to myofibroblasts → αSMA expression → opaque scar. Low TGF-β → transparent repair." },
  { id: 19, question: "What is the corneal endothelial cell density at birth vs. normal adult, and what is the threshold for decompensation?", answer: "At birth: ~3,500–4,000 cells/mm². Normal adult: ~2,000–2,500 cells/mm². Decompensation threshold: ~500 cells/mm² (though this varies). Endothelial cells do NOT proliferate in vivo — they spread and enlarge to compensate for cell loss (polymegethism and pleomorphism)." },
  { id: 20, question: "What is the role of matrix metalloproteinases (MMPs) in corneal disease?", answer: "MMPs (especially MMP-1, -2, -9) degrade stromal collagen. In normal wound healing, MMPs facilitate epithelial migration. In pathology: excess MMP-9 in dry eye disease damages the epithelial glycocalyx; Pseudomonas and S. aureus activate MMPs causing rapid stromal melting (keratolysis). MMP inhibition (doxycycline, EDTA) is used therapeutically." },
  { id: 21, question: "What nerve fibers terminate in the corneal epithelium and at what cell layer?", answer: "Long ciliary nerves (from CN V1) enter the deep peripheral stroma radially, lose myelination near the limbus, course anteriorly, penetrate Bowman layer, and form a subepithelial plexus. Free nerve endings terminate at the wing cell level of the epithelium — making the cornea the most densely innervated surface tissue in the body." },
  { id: 22, question: "What is substance P and what is its role in corneal physiology?", answer: "Substance P is a neuropeptide released by trigeminal nerve endings in the cornea. It promotes epithelial cell migration, proliferation, and adhesion to fibronectin — essential for wound healing. Trigeminal nerve damage → depletion of substance P → impaired epithelial healing → neurotrophic keratopathy." },
  { id: 23, question: "What distinguishes the lipid layer composition of the tear film and which glands produce it?", answer: "Meibomian glands (modified sebaceous glands in the tarsal plate) secrete meibum. It contains ~95% nonpolar lipids (wax esters, cholesterol esters) and ~5% amphipathic lipids (OAHFAs — the major surfactants). Meibomian gland dysfunction (MGD) → evaporative dry eye, the most common dry eye subtype." },
  { id: 24, question: "What is the plica semilunaris and what is its clinical relevance?", answer: "The plica semilunaris is a crescent-shaped fold of conjunctiva at the medial canthus, representing the vestigial third eyelid (nictitating membrane). Fine fibrous strips from the medial rectus insert into it. It accommodates eye movement in adduction. Foreign bodies frequently lodge here — always evert and inspect." },
  { id: 25, question: "What proteoglycans are present in the corneal stroma and what is their function?", answer: "Keratan sulfate proteoglycans (lumican, keratocan, mimecan) and dermatan sulfate proteoglycans (decorin, biglycan). They regulate collagen fibril diameter and interfibrillar spacing — critical for maintaining the precise arrangement needed for transparency. In corneal scarring, proteoglycan composition changes → disrupted fibril arrangement → opacity." },
];

const CORNEA_BASIC_MCQ: MCQ[] = [
  {
    id: 1,
    question: "A 58-year-old with herpes zoster ophthalmicus has a painless corneal ulcer unresponsive to antibiotics. Corneal sensation is absent. Which mechanism best explains the non-healing?",
    options: ["Viral replication causing direct cytopathic epithelial damage", "Loss of trophic neuropeptides (substance P, IGF-1) impairing epithelial maintenance", "Autoimmune T-cell destruction of limbal stem cells", "Endothelial pump failure causing epithelial edema"],
    correct: 1,
    explanation: "Neurotrophic keratopathy results from trigeminal denervation. Corneal nerves provide trophic support (substance P, IGF-1) essential for epithelial healing — not just sensation. The painless nature is the diagnostic key. Antibiotics are ineffective because the pathology is neurogenic, not infectious.",
  },
  {
    id: 2,
    question: "A researcher notes that unlike sclera, corneal stroma is transparent despite being primarily collagen. Which structural property is MOST responsible?",
    options: ["Absence of proteoglycans between fibrils", "Uniform fibril diameter and spacing less than half the wavelength of visible light", "High stromal water content preventing light absorption", "Large-diameter fibrils oriented parallel to the visual axis"],
    correct: 1,
    explanation: "Transparency requires destructive interference of scattered light waves. This occurs only when fibrils are uniform in diameter and spaced at distances <200 nm (less than half wavelength of visible light ~400 nm). Scleral fibrils are irregular in diameter and randomly spaced — hence opaque.",
  },
  {
    id: 3,
    question: "A 72-year-old with Fuchs endothelial dystrophy has diffuse guttae and microcystic epithelial edema. Why does endothelial failure cause epithelial changes?",
    options: ["Endothelial cytokines directly disrupt epithelial tight junctions", "Failed Na⁺/K⁺-ATPase pump causes stromal water accumulation propagating anteriorly", "Descemet membrane rupture allows aqueous to flood the stroma", "Reduced aqueous production depletes epithelial nutrients"],
    correct: 1,
    explanation: "The endothelium actively pumps fluid into the anterior chamber against an osmotic gradient. Failure (Fuchs) allows water to accumulate in the stroma. Edema propagates anteriorly: stromal edema → subepithelial bullae → microcystic epithelial edema → painful bullous keratopathy in advanced stages.",
  },
  {
    id: 4,
    question: "A 35-year-old with Stevens-Johnson syndrome develops corneal pannus and vascularization. What is the MOST direct cause?",
    options: ["Inflammatory cytokines stimulate corneal stromal angiogenesis", "Limbal stem cell destruction allows vascularized conjunctival epithelium to invade the cornea", "Collagen disorganization after erosions permits vessel ingrowth", "Endothelial failure causes hypoxic stimulus for neovascularization"],
    correct: 1,
    explanation: "Limbal stem cells act as a barrier preventing conjunctival epithelial migration onto the cornea. When destroyed (LSCD from SJS, chemical burns, aniridia), conjunctival cells — which bring their native vasculature — invade the corneal surface. This is the hallmark of LSCD: pannus, vascularization, and conjunctivalization.",
  },
  {
    id: 5,
    question: "A contact lens wearer presents with a Pseudomonas corneal ulcer. Which component of the corneal defense barrier was MOST likely breached?",
    options: ["Corneal endothelium — primary immune barrier", "Bowman layer — blocks bacterial penetration into stroma", "Epithelial tight junctions and antimicrobial tear film proteins", "Stromal keratocytes — normally phagocytose bacteria"],
    correct: 2,
    explanation: "The corneal epithelium and tear film (lysozyme, lactoferrin, IgA) form the primary defense. Contact lens wear disrupts this via microtrauma, hypoxia, and altered tear dynamics. Pseudomonas uniquely secretes collagenase and exotoxins that cause rapid stromal melt once the epithelial barrier is breached.",
  },
  {
    id: 6,
    question: "A 19-year-old sustains a sodium hydroxide (alkali) ocular burn. Why is alkali more penetrating and destructive than acid?",
    options: ["Alkali has a higher molecular weight allowing deeper tissue penetration", "Alkali causes saponification of membrane lipids, enabling continued penetration without self-limiting protein precipitation", "Alkali activates corneal MMP-9 while acid does not", "Alkali selectively destroys Bowman layer, removing the natural barrier to deeper penetration"],
    correct: 1,
    explanation: "Acid burns cause protein precipitation at the injury site that limits further penetration (self-limiting). Alkali saponifies cell membrane lipids, allowing continued penetration into deeper structures including the anterior chamber. This is why alkali burns are ophthalmic emergencies requiring immediate and prolonged irrigation.",
  },
  {
    id: 7,
    question: "A patient has Fuchs dystrophy with endothelial cell density of 450 cells/mm². A normal young adult has approximately how many endothelial cells/mm²?",
    options: ["500–800 cells/mm²", "2,000–2,500 cells/mm²", "4,000–5,000 cells/mm²", "8,000–10,000 cells/mm²"],
    correct: 1,
    explanation: "Normal adult corneal endothelial density is ~2,000–2,500 cells/mm². Decompensation typically occurs below ~500 cells/mm². Critically, endothelial cells do NOT regenerate in vivo — remaining cells spread and enlarge (polymegethism and pleomorphism) to cover the defect, reducing functional reserve further.",
  },
  {
    id: 8,
    question: "A 28-year-old with aniridia (PAX6 mutation) develops corneal pannus. What is the primary pathophysiology?",
    options: ["PAX6 mutation causes primary endothelial dysfunction", "PAX6 haploinsufficiency results in qualitatively abnormal limbal stem cells unable to maintain the corneal surface", "Iris absence exposes cornea to UV phototoxicity", "PAX6 mutation disrupts type I collagen synthesis"],
    correct: 1,
    explanation: "PAX6 is the master transcription factor for ocular development. PAX6 haploinsufficiency (aniridia) causes qualitatively deficient LSCs — they lack normal self-renewal capacity. The corneal surface degenerates over years, leading to LSCD with pannus and conjunctivalization — a major cause of vision loss independent of the iris defect.",
  },
  {
    id: 9,
    question: "A researcher studies corneal wound healing and observes that keratocytes near the wound undergo apoptosis within 6 hours. What triggers this?",
    options: ["Direct mechanical trauma from the injury", "IL-1α and FasL released from wounded epithelial cells signal keratocyte apoptosis", "Aqueous humor cytokines reaching the stroma via endothelial gaps", "Reactive oxygen species from neutrophils infiltrating the wound"],
    correct: 1,
    explanation: "Injured corneal epithelium releases IL-1α (stored in epithelial cells) and FasL, which diffuse into the stroma and trigger keratocyte apoptosis within hours. This clears the wound zone for subsequent keratocyte repopulation by peripheral cells. Dysregulation — excess TGF-β — drives myofibroblast transformation and stromal haze.",
  },
  {
    id: 10,
    question: "An ophthalmology resident notes corneal nerve fibers lose their myelination shortly after entering the cornea. What is the clinical significance of this?",
    options: ["Demyelinated fibers transmit only pain, not touch or temperature", "Unmyelinated corneal nerve endings allow confocal microscopy visualization and explain why corneal sensation is purely via free nerve endings", "Loss of myelin prevents viral spread along corneal nerves", "Demyelination increases nerve fiber vulnerability to herpes simplex virus latency"],
    correct: 1,
    explanation: "Corneal nerve fibers lose their myelin sheath within 1–2 mm of limbal entry. This means all corneal innervation is via unmyelinated free nerve endings (the densest in the body). These can be visualized in vivo by confocal microscopy. Their loss correlates directly with decreased corneal sensation.",
  },
  {
    id: 11,
    question: "A dry eye patient has normal Schirmer test results but severely reduced tear film breakup time (TBUT < 5 seconds). Which layer of the tear film is MOST likely deficient?",
    options: ["Aqueous layer — from lacrimal gland", "Mucin layer — from conjunctival goblet cells", "Lipid layer — from meibomian glands", "Electrolyte component — from accessory lacrimal glands"],
    correct: 2,
    explanation: "Normal aqueous production (normal Schirmer) with rapid tear film breakup indicates evaporative dry eye due to meibomian gland dysfunction (MGD). The lipid layer prevents aqueous evaporation. Without it, tears evaporate rapidly → TBUT shortens → hyperosmolarity → ocular surface inflammation. MGD is the most common cause of dry eye.",
  },
  {
    id: 12,
    question: "During corneal transplant surgery, the surgeon notes the recipient stroma appears hazy with an irregular surface. Histology shows disrupted proteoglycan composition. Which proteoglycans are normally critical for stromal transparency?",
    options: ["Aggrecan and versican (large aggregating proteoglycans)", "Lumican and keratocan (small leucine-rich keratan sulfate proteoglycans)", "Perlecan and agrin (heparan sulfate proteoglycans)", "Syndecan and glypican (membrane-bound proteoglycans)"],
    correct: 1,
    explanation: "Lumican and keratocan are the predominant corneal keratan sulfate proteoglycans. They regulate collagen fibril diameter and interfibrillar spacing. In corneal scars, proteoglycan composition reverts to non-corneal types (dermatan sulfate), disrupting fibril spacing → opacity. This is the molecular basis of corneal scarring.",
  },
  {
    id: 13,
    question: "A 45-year-old woman with Sjögren syndrome has severe dry eye with markedly reduced goblet cells on impression cytology. Which mucin is MOST critically depleted?",
    options: ["MUC1 (transmembrane mucin of corneal glycocalyx)", "MUC5AC (secreted gel-forming mucin from goblet cells)", "MUC16 (transmembrane mucin providing barrier function)", "MUC4 (transmembrane mucin of conjunctival glycocalyx)"],
    correct: 1,
    explanation: "MUC5AC is the primary gel-forming secreted mucin of the tear film, produced exclusively by conjunctival goblet cells. It is responsible for tear film viscosity and stability. Its depletion in Sjögren syndrome (immune-mediated goblet cell destruction) causes mucin-deficient dry eye with poor TBUT despite relatively preserved aqueous production.",
  },
  {
    id: 14,
    question: "A 55-year-old man develops corneal melt (keratolysis) following a Pseudomonas ulcer despite 48 hours of fluoroquinolone therapy. Which pathophysiologic mechanism is driving the rapid stromal destruction?",
    options: ["Continued Pseudomonas replication producing direct proteolytic enzymes", "Pseudomonas-activated plasmin generates MMP-1 from infected myofibroblasts, synergistically degrading stromal collagen", "Neutrophil-derived reactive oxygen species degrading collagen fibrils", "IL-1-mediated keratocyte apoptosis leaving acellular stroma susceptible to autolysis"],
    correct: 1,
    explanation: "S. aureus and Pseudomonas activate the plasminogen/plasmin system in the cornea. Plasmin directly degrades ECM but also activates MMP-1 from myofibroblasts, creating a cascade of collagen destruction. This explains why bacterial keratitis can rapidly progress to perforation even with appropriate antibiotics — the inflammatory cascade must also be targeted.",
  },
  {
    id: 15,
    question: "A 32-year-old undergoes PRK for myopia correction. Six weeks postoperatively, she develops subepithelial haze. What cellular event is MOST responsible?",
    options: ["Persistent epithelial defect releasing proteases that degrade Bowman layer", "TGF-β diffusing from tears drives keratocyte-to-myofibroblast transformation in the anterior stroma", "Epithelial hyperplasia filling the ablation zone and scattering light", "Inadequate keratocyte repopulation leaving acellular stroma that scatters light"],
    correct: 1,
    explanation: "PRK disrupts Bowman layer, allowing TGF-β from tears to penetrate the anterior stroma. TGF-β drives keratocyte differentiation into myofibroblasts (α-SMA positive), which produce disorganized ECM — opaque subepithelial haze. LASIK creates a stromal flap preserving Bowman layer, reducing TGF-β access — hence less haze.",
  },
  {
    id: 16,
    question: "Tear film osmolarity is measured at 320 mOsm/L (normal <308 mOsm/L). This hyperosmolarity initiates which inflammatory cascade?",
    options: ["Complement activation via the lectin pathway targeting goblet cell surface antigens", "Activation of MAP kinase (p38, JNK) and NF-κB pathways releasing IL-1, TNF-α, and MMP-9", "TLR-4 activation by osmotic stress proteins triggering innate immune response", "NLRP3 inflammasome activation releasing IL-18 from epithelial cells"],
    correct: 1,
    explanation: "Tear hyperosmolarity directly activates MAP kinase signaling (p38, JNK, ERK) and NF-κB in corneal epithelial cells. This releases pro-inflammatory cytokines (IL-1, TNF-α) and MMP-9, which degrades the epithelial glycocalyx. The resulting epithelial damage increases evaporation → further hyperosmolarity — the vicious cycle of dry eye disease.",
  },
  {
    id: 17,
    question: "Which statement best describes the embryological origin of the corneal endothelium?",
    options: ["Mesoderm — endothelium shares lineage with vascular endothelium throughout the body", "Neural crest cells (neuroectoderm) — which also form the stroma and Descemet membrane", "Surface ectoderm — the same origin as the corneal epithelium", "Periocular mesenchyme of mixed mesodermal and neural crest origin"],
    correct: 1,
    explanation: "The corneal endothelium, stroma, and Descemet membrane all derive from neural crest cells that migrate into the anterior segment during weeks 5–8 of gestation. This explains why conditions affecting neural crest development (Peters anomaly, Axenfeld-Rieger, CHED) involve both endothelium and stroma simultaneously.",
  },
  {
    id: 18,
    question: "A patient with cicatricial pemphigoid has severe conjunctival scarring with subconjunctival fibrosis. Which mechanism best explains the progressive scarring?",
    options: ["IgG autoantibodies against BP180 causing direct conjunctival cell lysis", "Chronic TGF-β release from injured epithelium driving subconjunctival fibroblast-to-myofibroblast transformation", "Complement-mediated destruction of goblet cells releasing pro-fibrotic signals", "IL-17-mediated neutrophil infiltration causing proteolytic degradation and subsequent fibrosis"],
    correct: 1,
    explanation: "In mucous membrane pemphigoid, autoantibody-mediated epithelial injury persistently releases TGF-β. This drives subconjunctival fibroblasts to myofibroblasts, which contract and deposit disorganized collagen — producing the symblepharon, fornix shortening, and entropion characteristic of advanced disease.",
  },
  {
    id: 19,
    question: "Confocal microscopy in a patient with keratoconus shows reduced subbasal nerve plexus density. Which clinical finding would you MOST expect?",
    options: ["Increased intraocular pressure from impaired aqueous outflow", "Reduced corneal sensation with paradoxically increased pain sensitivity (neuropathic pain)", "Elevated corneal endothelial cell density compensating for nerve loss", "Decreased corneal transparency due to nerve-induced collagen changes"],
    correct: 1,
    explanation: "Reduced subbasal nerve plexus density in keratoconus correlates with decreased corneal sensation (esthesiometry). Paradoxically, neuropathic changes can cause heightened pain sensitivity (allodynia) even with reduced mechanical sensation. This is clinically relevant — reduced sensation may mask contact lens complications.",
  },
  {
    id: 20,
    question: "A surgeon plans to harvest a conjunctival autograft for pterygium surgery. The graft is taken from the superotemporal bulbar conjunctiva. Which cell type in the graft is MOST responsible for its success in preventing recurrence?",
    options: ["Conjunctival fibroblasts providing structural support", "Limbal epithelial stem cells and their trophic influence on the ocular surface", "Goblet cells restoring mucin production to the pterygium bed", "Antigen-presenting Langerhans cells preventing UV-mediated recurrence"],
    correct: 1,
    explanation: "Conjunctival autograft success depends critically on including limbal tissue from the graft margin. Limbal stem cells transferred with the graft repopulate the surgical site and prevent conjunctival epithelium from re-growing over the cornea. Bare sclera techniques have high recurrence; autografts including limbal tissue have the lowest recurrence rates.",
  },
  {
    id: 21,
    question: "Which statement about the Bowman layer is CORRECT?",
    options: ["It is a true basement membrane secreted by the basal epithelial cells", "It is an acellular condensation of the anterior stroma that does not regenerate after injury", "It plays an essential role in corneal transparency that has been confirmed in all mammalian species studied", "It contains type IV collagen as its primary structural component"],
    correct: 1,
    explanation: "The Bowman layer is an acellular condensation of the anterior stroma — not a true basement membrane. It does NOT regenerate after injury (replaced by fibrous tissue/scar). Many mammals (rabbits, cats) lack a Bowman layer yet have normal corneal structure, suggesting it is not essential for transparency or epithelial organization.",
  },
  {
    id: 22,
    question: "A patient has severe aqueous deficient dry eye from lacrimal gland destruction. Measurement shows tear film thickness of 1.5 µm (normal 2–5.5 µm). What is the MOST important consequence for corneal function?",
    options: ["Reduced oxygen delivery causing hypoxic epithelial damage", "Increased exposure to environmental UV radiation causing photokeratitis", "Disruption of the first refracting surface causing irregular astigmatism and visual distortion", "Loss of IgA allowing bacterial colonization of the corneal surface"],
    correct: 2,
    explanation: "The tear film is the FIRST refracting surface light encounters. Even minor irregularities in tear film quality dramatically degrade optical quality (measured by double-pass aberrometry). This is why dry eye patients complain of fluctuating vision that improves transiently after blinking — the blink restores a smooth refracting surface.",
  },
  {
    id: 23,
    question: "A 60-year-old diabetic patient has delayed corneal epithelial healing after cataract surgery. Which factor MOST directly explains his impaired epithelial wound healing?",
    options: ["Hyperglycemia reducing epithelial cell glycolysis and ATP production", "Diabetic autonomic neuropathy reducing corneal nerve density and trophic factor release", "Advanced glycation end-products cross-linking Bowman layer collagen, impeding cell migration", "Hyperglycemia-induced overexpression of MMP-9 degrading the epithelial basement membrane"],
    correct: 1,
    explanation: "Diabetic keratopathy is primarily a neurotrophic condition. Diabetes causes corneal neuropathy (reduced subbasal nerve density correlating with peripheral neuropathy severity) → reduced substance P, NGF, and IGF-1 → impaired epithelial proliferation and migration. This explains the high rate of epithelial complications in diabetic patients after any ocular surgery.",
  },
  {
    id: 24,
    question: "The stroma constitutes what percentage of total corneal thickness?",
    options: ["50%", "70%", "90%", "95%"],
    correct: 2,
    explanation: "The stroma constitutes more than 90% of total corneal thickness — approximately 500 µm of the ~550 µm total. It consists of ~200 collagen lamellae, each containing parallel fibrils at angles to adjacent lamellae. This orthogonal arrangement provides mechanical strength while maintaining the precise fibril spacing required for transparency.",
  },
  {
    id: 25,
    question: "A patient undergoes total conjunctival resection for ocular surface squamous neoplasia. Postoperatively, she develops persistent epithelial defects and dry eye. Which function of the conjunctiva is MOST responsible for these complications?",
    options: ["Conjunctival vascular supply to the avascular limbus", "Goblet cell mucin secretion and limbal stem cell reservoir support", "Lymphatic drainage preventing corneal edema", "Immune surveillance via subepithelial lymphocytes"],
    correct: 1,
    explanation: "The conjunctiva provides two critical functions lost with resection: goblet cells (MUC5AC for tear film stability) and the limbal niche microenvironment that supports LSCs. Without goblet cell mucins, the tear film destabilizes. Without conjunctival support of the limbal niche, LSC function is compromised — causing epithelial instability and persistent defects.",
  },
  {
    id: 26,
    question: "In the XYZ model of corneal epithelial homeostasis, what happens if Y (centripetal movement) ceases while X (proliferation) continues?",
    options: ["The epithelium thins centrally and accumulates excess cells peripherally", "Central epithelial cells accumulate, become dysplastic, and develop features of squamous metaplasia", "Limbal stem cells exhaust prematurely due to compensatory overproliferation", "The Z component (desquamation) increases to compensate, maintaining overall balance"],
    correct: 2,
    explanation: "If centripetal movement stops (e.g., limbal stem cell deficiency) while basal cells still proliferate, LSCs are forced into excessive asymmetric division without the normal amplifying cell migration to distribute the load. This depletes the LSC pool prematurely — the basis of iatrogenic LSCD from repeated pterygium surgery or chronic topical medication toxicity.",
  },
  {
    id: 27,
    question: "A corneal specimen shows disrupted collagen fibril arrangement with areas of fibril fusion and irregular spacing. Which corneal disease does this pattern MOST suggest?",
    options: ["Keratoconus — characterized by fibril thinning and proteoglycan loss", "Fuchs endothelial dystrophy — characterized by posterior collagen deposition (guttae)", "Lattice corneal dystrophy — characterized by amyloid deposits distorting fibril arrangement", "Macular corneal dystrophy — caused by defective keratan sulfate synthesis disrupting fibril spacing"],
    correct: 3,
    explanation: "Macular corneal dystrophy (CHST6 mutation) impairs keratan sulfate sulfation → defective proteoglycans cannot maintain normal fibril spacing → fibrils are irregular in diameter and spacing throughout the full stromal thickness → diffuse stromal haze from birth. Unlike granular/lattice dystrophies, macular involves the full stroma and has autosomal recessive inheritance.",
  },
  {
    id: 28,
    question: "A patient reports that their vision improves for a few seconds after each blink then gradually blurs until the next blink. Which diagnostic test would MOST specifically quantify this complaint?",
    options: ["Schirmer test — measures aqueous tear production volume", "Tear film breakup time (TBUT) — measures time to first dry spot formation", "Tear osmolarity — measures electrolyte concentration imbalance", "Impression cytology — measures goblet cell density"],
    correct: 1,
    explanation: "The described symptom is classic for evaporative dry eye — tear film instability causing visual fluctuation. TBUT directly measures this: fluorescein is instilled, the patient blinks once and holds open; the time to first dark spot (dry area) is measured. Normal TBUT >10 seconds; <5 seconds indicates significant instability.",
  },
  {
    id: 29,
    question: "Which collagen type is the primary component of Descemet membrane and the corneal basement membranes?",
    options: ["Type I collagen — the same as the bulk stroma", "Type IV collagen — the characteristic collagen of all basement membranes", "Type VII collagen — anchoring fibrils at the epithelial-stromal junction", "Type XVIII collagen — providing anti-angiogenic properties"],
    correct: 1,
    explanation: "Type IV collagen is the characteristic collagen of all basement membranes in the body, forming a sheet-like network rather than fibrils. Descemet membrane (the endothelial basement membrane) thickens throughout life from ~3 µm at birth to ~10–12 µm in adults, and continues to thicken abnormally in Fuchs dystrophy (producing guttae) and CHED.",
  },
  {
    id: 30,
    question: "A 40-year-old patient develops neurotrophic keratopathy following acoustic neuroma resection. Which treatment directly targets the pathophysiologic mechanism of non-healing?",
    options: ["Topical fluoroquinolone to prevent superinfection of the epithelial defect", "Cenegermin (recombinant human nerve growth factor) eye drops to restore epithelial trophic support", "Topical corticosteroids to reduce neurogenic inflammation", "Amniotic membrane transplant to provide a structural scaffold for epithelial migration"],
    correct: 1,
    explanation: "Cenegermin (recombinant human NGF, Oxervate) directly replaces the trophic support lost after trigeminal nerve damage. NGF binds TrkA receptors on corneal epithelial cells, promoting proliferation, differentiation, and migration. It received FDA approval in 2018 as the first drug specifically targeting the pathophysiology of neurotrophic keratopathy.",
  },
];

// ── Retina · BCSC Section 12 · Part 1 · Fluorescein & ICG Angiography
// Source: BCSC Section 12 (Retina and Vitreous), Ch. 2 (Diagnostic Approach).
const BCSC_FFA_RECALL: RecallQ[] = [
  { id: 1, question: "What wavelengths do the excitation and barrier filters transmit in fluorescein angiography?", answer: "Excitation filter: blue-green light at 465–490 nm (fluorescein's peak excitation). Barrier filter: yellow-green at 520–530 nm (fluorescein's peak emission). The barrier filter blocks essentially all visible wavelengths except the light emitted by fluorescein." },
  { id: 2, question: "What percentage of fluorescein is protein-bound, and why does that matter?", answer: "About 80% is protein-bound. The intact blood–retina barrier prevents fluorescein from diffusing into retinal tissue, so normal retinal vessels do not leak. Dye leaks only where a blood–ocular barrier is absent (new vessels) or defective (inflammation, ischemia)." },
  { id: 3, question: "From which structure does fluorescein readily leak, and what limits its use for choroidal imaging?", answer: "It leaks readily from the fenestrated choriocapillaris, staining surrounding tissue. That rapid leakage, plus light absorption and scattering by RPE and choroidal pigment, limits fluorescein's usefulness for choroidal imaging — ICG is preferred there." },
  { id: 4, question: "Describe the timing of the phases of a normal fluorescein angiogram.", answer: "Choroidal (prearterial) flush ~8–12 s; retinal arterial phase 11–18 s; arteriovenous phase 1–3 s later (with laminar venous flow); complete venous filling over the next 5–10 s; recirculation/mid phase at 2–4 min; late phase at 4–5 min (gradual dye elimination)." },
  { id: 5, question: "What is laminar venous flow on FA?", answer: "Thin columns of dye seen along the walls of the larger veins during the early arteriovenous phase before the veins fill completely — a consequence of the parabolic flow profile (faster central, slower peripheral wall flow)." },
  { id: 6, question: "Why does the fovea appear dark on fluorescein angiography?", answer: "Three reasons: macular xanthophyll pigment absorbs the blue excitation light; the foveal RPE cells are taller and contain more melanin than peripheral RPE; and there are no retinal vessels in the foveal avascular zone." },
  { id: 7, question: "What are the two major categories of FA abnormality?", answer: "Hypofluorescence (reduced or absent fluorescence) and hyperfluorescence (abnormally excessive fluorescence)." },
  { id: 8, question: "What are the two patterns of hypofluorescence?", answer: "Vascular filling defects (nonperfusion or obstruction of an artery, vein, or capillary — seen as delayed or absent filling) and blocked fluorescence (obstruction of the excitation or emitted light by pigment, blood, or fibrous tissue)." },
  { id: 9, question: "How can blocked fluorescence be used to determine a lesion's depth?", answer: "By relating the level of blocked fluorescence to the retinal circulation. If a lesion blocks the choroidal fluorescence but retinal vessels are seen coursing over it, the lesion lies above the choroid and beneath the retinal vessels." },
  { id: 10, question: "What are the four patterns of hyperfluorescence?", answer: "Leakage, staining, pooling, and transmission (window) defect." },
  { id: 11, question: "Define leakage and its behavior over the course of an FA.", answer: "A gradual, marked increase in fluorescence from seepage of dye across a compromised blood–retina barrier. Both brightness and size increase through the study and the borders become indistinct (e.g., CNV, neovascularization, active inflammation)." },
  { id: 12, question: "Define staining and how to recognize it.", answer: "Fluorescein entering solid tissue or material that retains dye — scar, drusen, vessel walls, optic nerve tissue, sclera. Fluorescence increases in brightness through transit and persists in late frames, but the borders remain fixed and intact (size does not change)." },
  { id: 13, question: "Define pooling and give a classic example.", answer: "Accumulation of dye within a fluid-filled space whose margins trap it, producing distinct borders (round/oval). Classic example: pooling under a serous RPE or neurosensory detachment in central serous chorioretinopathy." },
  { id: 14, question: "Define a transmission (window) defect and its time course.", answer: "A view of normal choroidal fluorescence through an RPE pigment defect. It appears early with choroidal filling, peaks with peak choroidal filling, does NOT enlarge, and fades in late frames as choroidal dye is diluted; the dye stays in the choroid and does not enter the retina." },
  { id: 15, question: "Summarize how brightness and size change over time for the four hyperfluorescence patterns.", answer: "Leakage: brightness ↑, size ↑. Staining: brightness ↑, size unchanged (irregular shape). Pooling: brightness same/↑, size unchanged (regular round/oval). Window defect: brightness decreases late, size unchanged." },
  { id: 16, question: "What is the inner blood–retina barrier, and what happens when it is compromised?", answer: "The tight junctions of the retinal vascular endothelium. When compromised, dye leaks through vessel walls into the retinal parenchyma and cystoid spaces (e.g., cystoid macular edema)." },
  { id: 17, question: "What is the outer blood–retina barrier, and what is the effect of its breakdown?", answer: "The retinal pigment epithelium (its tight junctions). When compromised, dye traverses the RPE into the subretinal space or neurosensory retina." },
  { id: 18, question: "What is the classic FA appearance of cystoid macular edema?", answer: "Late pooling of dye in petalloid cystoid spaces radiating from the central macula (Henle fiber layer), often with late staining of the optic nerve head — as seen in postsurgical (Irvine–Gass) CME." },
  { id: 19, question: "Contrast the FA appearance of classic versus occult CNV.", answer: "Classic CNV: an early, well-defined lacy hyperfluorescent network that leaks progressively, with pooling/leakage in the late phase. Occult CNV: poorly defined late leakage and staining without a discrete early network." },
  { id: 20, question: "What temporary and common adverse effects follow fluorescein injection?", answer: "Temporary yellowing of the skin and conjunctiva (6–12 h) and yellow-green urine; nausea and vomiting in ~5% (passes within seconds); and urticaria/hives in ~5% (treated with diphenhydramine unless very mild)." },
  { id: 21, question: "What serious adverse effects can occur with FA, and how is the risk managed?", answer: "Rare hypotension, shock, laryngeal spasm, and even death (~1:222,000). A physician should be on the premises and a crash cart available. Prior urticarial reactions raise the risk; premedication with antihistamines and/or corticosteroids reduces it." },
  { id: 22, question: "How is fluorescein extravasation managed, and what are the pregnancy/lactation considerations?", answer: "Extravasation into the skin is painful and treated with ice-cold compresses for 5–10 minutes and close follow-up until edema/pain/redness resolve. No teratogenicity is proven, but FA is generally avoided in the first trimester unless necessary; fluorescein is excreted in breast milk during lactation." },
  { id: 23, question: "What properties of indocyanine green make it ideal for choroidal imaging?", answer: "ICG is a water-soluble tricarbocyanine dye that is ~98% protein-bound, so it diffuses poorly through the choriocapillaris fenestrations and remains intravascular — ideal for imaging choroidal vessels. Its near-infrared excitation/emission also penetrates RPE, pigment, and blood better than fluorescein." },
  { id: 24, question: "What are ICG's excitation and emission wavelengths, and how is it cleared?", answer: "Excitation ~790–805 nm and emission ~825–835 nm, both in the near-infrared range. ICG is metabolized in the liver and excreted into the bile." },
  { id: 25, question: "Describe the phases of a normal ICG angiogram.", answer: "Early phase: first appearance of dye in the choroidal circulation (large choroidal arteries and veins plus retinal vessels visible). Middle phase (5–15 min): choroidal veins become indistinct with diffuse homogeneous choroidal fluorescence and reduced retinal vessel fluorescence. Late phase (~15 min): little retinal or choroidal detail remains." },
];

const BCSC_FFA_MCQ: MCQ[] = [
  { id: 1, question: "The excitation filter of a fundus camera set up for fluorescein angiography transmits light at:", options: ["520–530 nm yellow-green", "465–490 nm blue-green", "790–805 nm near-infrared", "620–640 nm red"], correct: 1, explanation: "The excitation filter passes blue-green light (465–490 nm, peak excitation); the barrier filter passes yellow-green light (520–530 nm, peak emission)." },
  { id: 2, question: "The barrier filter transmits light at approximately:", options: ["465–490 nm", "520–530 nm", "825–835 nm", "400–450 nm"], correct: 1, explanation: "The barrier filter passes fluorescein's emitted yellow-green light at 520–530 nm and blocks other visible wavelengths." },
  { id: 3, question: "Approximately what fraction of circulating fluorescein is protein-bound?", options: ["20%", "50%", "80%", "98%"], correct: 2, explanation: "Fluorescein is ~80% protein-bound; the free fraction fluoresces and can leak where barriers are defective. (ICG, by contrast, is ~98% bound.)" },
  { id: 4, question: "Fluorescein does NOT normally leak from retinal vessels because of:", options: ["Its large molecular size", "The intact inner blood–retina barrier (tight junctions of retinal endothelium)", "Rapid hepatic clearance", "Binding to RPE melanin"], correct: 1, explanation: "The inner blood–retina barrier (retinal vascular endothelial tight junctions) keeps dye intravascular in healthy retina." },
  { id: 5, question: "On a normal FA, the choroid typically begins to fill at:", options: ["1–3 seconds", "8–12 seconds", "20–25 seconds", "2–4 minutes"], correct: 1, explanation: "The choroidal flush appears at ~8–12 s, about a half-second before the retinal circulation; retinal arteries fill at 11–18 s." },
  { id: 6, question: "\"Laminar flow\" on fluorescein angiography refers to:", options: ["Uniform bright filling of the arteries", "Thin columns of dye along the walls of the larger veins during early venous filling", "Leakage from the choriocapillaris", "Dye pooling under the RPE"], correct: 1, explanation: "Laminar venous flow is the early arteriovenous-phase appearance of dye along vein walls before complete venous filling." },
  { id: 7, question: "The late phase of FA (gradual dye elimination) occurs at approximately:", options: ["15–18 seconds", "1 minute", "4–5 minutes", "20 minutes"], correct: 2, explanation: "Recirculation begins at 2–4 min, and the late phase (dye elimination) is seen at ~4–5 min." },
  { id: 8, question: "The fovea appears hypofluorescent (dark) on FA for all of the following reasons EXCEPT:", options: ["Macular xanthophyll pigment absorbs excitation light", "Taller foveal RPE cells with more melanin", "Absence of vessels in the foveal avascular zone", "A thickened internal limiting membrane at the fovea"], correct: 3, explanation: "The dark fovea reflects xanthophyll pigment, denser foveal RPE melanin, and the avascular FAZ — not the ILM." },
  { id: 9, question: "Hypofluorescence on FA is caused by which two mechanisms?", options: ["Leakage and staining", "Pooling and window defect", "Vascular filling defect and blocked fluorescence", "Transmission defect and leakage"], correct: 2, explanation: "The two hypofluorescence patterns are vascular filling (perfusion) defects and blocked fluorescence." },
  { id: 10, question: "A pigmented lesion blocks fluorescence, but retinal vessels are seen coursing over it. This localizes the lesion to:", options: ["The inner retina", "Anterior to the choroid, deep to the retinal vessels", "The vitreous cavity", "The optic nerve head"], correct: 1, explanation: "Depth is judged by which vessels are obscured; retinal vessels visible over a blocked choroid place the lesion between the two layers." },
  { id: 11, question: "Which hyperfluorescence pattern increases in BOTH brightness and size over the course of the study?", options: ["Staining", "Pooling", "Leakage", "Window defect"], correct: 2, explanation: "Leakage progressively increases in both brightness and area, with indistinct borders." },
  { id: 12, question: "A lesion that brightens through transit and persists late but keeps fixed, intact borders represents:", options: ["Leakage", "Staining", "Pooling", "Filling defect"], correct: 1, explanation: "Staining is dye entering solid retained material (scar, drusen, vessel wall, sclera, optic nerve) with unchanging borders." },
  { id: 13, question: "Late accumulation of dye within a serous RPE detachment, with sharply demarcated borders, is best described as:", options: ["Staining", "Pooling", "Window defect", "Blocked fluorescence"], correct: 1, explanation: "Pooling is dye trapped in a fluid-filled space with distinct margins, classically the RPE detachment of central serous chorioretinopathy." },
  { id: 14, question: "A transmission (window) defect characteristically:", options: ["Increases in size over the study", "Appears early, does not enlarge, and fades in late frames", "Leaks dye into the neurosensory retina", "Is brightest in the late phase"], correct: 1, explanation: "A window defect follows choroidal fluorescence: early appearance, peak with choroidal filling, no enlargement, and late fading as choroidal dye dilutes." },
  { id: 15, question: "Which pattern is characterized by decreasing brightness and unchanged size over time?", options: ["Leakage", "Pooling", "Staining", "Window (transmission) defect"], correct: 3, explanation: "The window defect dims in late frames (choroidal dye dilution) and never enlarges." },
  { id: 16, question: "Geographic atrophy exposing bare choroid through absent RPE produces which FA finding?", options: ["Leakage", "A transmission (window) defect", "Blocked fluorescence", "Pooling"], correct: 1, explanation: "Loss of RPE pigment unmasks normal choroidal fluorescence — an early window defect that fades late without leaking." },
  { id: 17, question: "The outer blood–retina barrier is formed by:", options: ["Retinal vascular endothelial tight junctions", "The retinal pigment epithelium", "Müller cell foot plates", "The internal limiting membrane"], correct: 1, explanation: "The RPE tight junctions form the outer BRB; the retinal endothelium forms the inner BRB." },
  { id: 18, question: "Cystoid macular edema from inner blood–retina barrier breakdown appears on FA as:", options: ["An early window defect", "Late petalloid pooling in the central macula with optic disc staining", "Blocked fluorescence", "Early bright staining of drusen"], correct: 1, explanation: "CME shows late petalloid pooling (Henle layer) and disc staining — classically Irvine–Gass after cataract surgery." },
  { id: 19, question: "On FA, \"classic\" choroidal neovascularization is characterized by:", options: ["A poorly defined area of late staining only", "An early, well-defined lacy hyperfluorescent network with progressive leakage", "Blocked fluorescence throughout the study", "An early window defect that fades late"], correct: 1, explanation: "Classic CNV is a discrete early network that leaks; occult CNV shows late, poorly defined leakage/staining." },
  { id: 20, question: "Drusen typically appear on FA as:", options: ["Early blocked fluorescence", "Staining — hyperfluorescence that increases then persists with fixed borders", "Progressive leakage with expanding borders", "Pooling under a detachment"], correct: 1, explanation: "Drusen stain: they take up and retain dye without leaking or expanding." },
  { id: 21, question: "The most common adverse effects of fluorescein injection are:", options: ["Anaphylaxis and shock", "Nausea/vomiting and urticaria, each in ~5%", "Seizures", "Permanent skin staining"], correct: 1, explanation: "Nausea/vomiting (~5%) and hives (~5%) are most common; nausea passes in seconds and hives respond to diphenhydramine." },
  { id: 22, question: "A patient's skin and urine turn yellow-green after FA. The appropriate action is:", options: ["Emergent evaluation for hepatic failure", "Reassurance — this is expected and resolves within hours", "Administer diphenhydramine", "Start IV corticosteroids"], correct: 1, explanation: "Skin/conjunctival yellowing (6–12 h) and discolored urine are universal, expected, and benign." },
  { id: 23, question: "The estimated risk of death from fluorescein angiography is approximately:", options: ["1:2,000", "1:22,000", "1:222,000", "1:2,000,000"], correct: 2, explanation: "Fatal reactions are rare, ~1:222,000; a physician and crash cart should nonetheless be available." },
  { id: 24, question: "A patient had urticaria after a prior fluorescein study and now needs another FA. The best approach is:", options: ["Refuse FA permanently", "Premedicate with antihistamines ± corticosteroids", "Use half the usual dye dose", "No precautions are needed"], correct: 1, explanation: "Prior urticaria increases recurrence risk; premedication with antihistamines and/or steroids reduces it." },
  { id: 25, question: "Painful extravasation of fluorescein into the skin during injection is managed with:", options: ["Warm compresses", "Ice-cold compresses for 5–10 minutes with close follow-up", "Incision and drainage", "Systemic antibiotics"], correct: 1, explanation: "Cold compresses and observation until swelling and pain resolve are recommended." },
  { id: 26, question: "Regarding FA in pregnancy and lactation:", options: ["It is absolutely contraindicated throughout pregnancy", "It is proven teratogenic", "It is often avoided in the first trimester (though no teratogenicity is proven) and the dye passes into breast milk", "It is completely safe with no considerations"], correct: 2, explanation: "No teratogenicity is proven, but many clinicians avoid the first trimester; fluorescein is excreted in breast milk." },
  { id: 27, question: "Indocyanine green is superior to fluorescein for imaging the choroid mainly because:", options: ["It is not protein-bound, so it diffuses freely", "It is ~98% protein-bound and near-infrared, so it stays intravascular and penetrates the RPE", "It is excreted renally", "It fluoresces in the ultraviolet range"], correct: 1, explanation: "High protein binding limits diffusion through choriocapillaris fenestrations, and near-infrared light penetrates pigment/blood — ideal for choroidal imaging." },
  { id: 28, question: "ICG excitation and emission peaks lie in which part of the spectrum?", options: ["Ultraviolet", "Blue-green", "Near-infrared (~790–835 nm)", "Red"], correct: 2, explanation: "ICG excitation ~790–805 nm and emission ~825–835 nm are both near-infrared." },
  { id: 29, question: "Indocyanine green is cleared by:", options: ["Renal excretion", "Hepatic metabolism and biliary excretion", "Exhalation", "RPE phagocytosis"], correct: 1, explanation: "ICG is metabolized by the liver and excreted into the bile." },
  { id: 30, question: "In the middle phase of a normal ICG angiogram (5–15 minutes), you expect:", options: ["First appearance of dye in the choroidal arteries", "Indistinct choroidal veins with diffuse homogeneous choroidal fluorescence and diminished retinal vessel fluorescence", "Complete absence of any fluorescence", "Bright leakage from the retinal capillaries"], correct: 1, explanation: "The middle phase shows fading choroidal vein detail with diffuse choroidal fluorescence and reduced retinal vessel signal." },
];

// ── Cornea · Mannis · Part 4 · Dry Eye & Ocular Allergy Medications
// Source: "Medication for Dry Eye and Ocular Allergy" (TFOS DEWS III–based lecture).
const CORNEA_MEDS_RECALL: RecallQ[] = [
  { id: 1, question: "What is the TFOS DEWS III definition of dry eye?", answer: "A multifactorial, symptomatic disease characterized by loss of homeostasis of the tear film and/or the ocular surface, in which tear film instability, hyperosmolarity, ocular surface inflammation and damage, and neurosensory abnormalities play etiological roles." },
  { id: 2, question: "What are the Step 1 (baseline / mild) interventions for dry eye?", answer: "Patient education and lifestyle modification, elimination of offending medications, low-viscosity lubrication, and lid hygiene with warm compresses for MGD." },
  { id: 3, question: "What defines Step 2 (moderate) dry eye management?", answer: "Advanced lubrication (preservative-free artificial tears, osmoprotectants, or hyaluronic acid), secretagogues, anti-inflammatory therapy, and doxycycline or azithromycin for chronic blepharitis/MGD." },
  { id: 4, question: "What are Steps 3 and 4 of dry eye management?", answer: "Step 3 (severe): biological substitutes (autologous serum/PRP) and mechanical interventions (punctal occlusion, contact lens, moisture chamber spectacles). Step 4 (refractory): surgery — tarsorrhaphy or amniotic membrane transplant." },
  { id: 5, question: "What is the trade-off of viscosity-enhancing artificial tears?", answer: "Higher viscosity increases tear residence/retention time and comfort, but causes transient blurring of vision and unwanted debris on the eyelids." },
  { id: 6, question: "Which cellulose demulcent is notable for promoting epithelial healing?", answer: "Carboxymethylcellulose (CMC) — a high-molecular-weight cellulose derivative that can promote epithelial healing. Cellulose derivatives (CMC, HPMC, HMC) are the most widely used demulcents." },
  { id: 7, question: "What is the role of Dextran 70 in artificial tears?", answer: "A high-molecular-weight (70 kDa) polysaccharide that enhances demulcent quality when combined with another demulcent (e.g., 0.3% HPMC + 0.1% dextran 70)." },
  { id: 8, question: "How do cationic oil-in-water nanoemulsion tears improve retention?", answer: "The positively charged oil nanodroplets are electrostatically attracted to the negatively charged ocular surface mucin, improving spreading and retention time; they also replace the lipid layer (nanoemulsion droplet size 10–100 nm)." },
  { id: 9, question: "What is an emollient (ointment) tear, and when is it used?", answer: "An ointment of petroleum/lanolin/mineral oils with higher viscosity and longer residence than demulcents, but it causes blurry vision and eyelash drying. Used for severe dry eye, at night, and for exposure keratopathy." },
  { id: 10, question: "What are the key properties of hyaluronic acid, and its residence-time advantage?", answer: "A glycosaminoglycan (sodium hyaluronate) that is water-retaining and mucoadhesive, giving tear film stability and healing of epithelial defects. 0.2% HA has significantly longer ocular surface residence time than 0.3% HPMC or 1.4% PVA." },
  { id: 11, question: "What is normal tear osmolarity, and the rationale for hypo-osmolar drops?", answer: "Normal tear osmolarity is 296–308 mOsm/L; dry eye causes hyperosmolarity. Hypo-osmolar eye drops lower the elevated tear osmolarity back toward normal." },
  { id: 12, question: "What are osmoprotectants and their effects?", answer: "Compounds (L-carnitine, erythritol, betaine, trehalose, glycerol) that protect cells under osmotic stress by balancing osmotic pressure without disturbing cell metabolism. They decrease apoptosis and inflammatory cytokines, increase goblet cells, and reduce corneal staining." },
  { id: 13, question: "Name the two classes of eye-drop preservatives with examples and relative toxicity.", answer: "Detergents (disrupt microbial cell membranes; high ocular toxicity) — benzalkonium chloride (BAK), Polyquad, cetrimide. Oxidizing agents (disrupt microbial metabolism; gentle on human tissue) — sodium perborate (Genaqua) and stabilized oxychloro complex (SOC/Purite)." },
  { id: 14, question: "What is the usage limit for preserved eye drops, and why?", answer: "Preserved drops should be used ≤4 times/day; using more than 4×/day for a long period causes preservative sensitivity/toxicity. Preservatives do help prevent contamination and can enhance corneal penetration of some drugs." },
  { id: 15, question: "Which electrolytes are most critical in artificial tears, and what are their roles?", answer: "Potassium (K) and bicarbonate (HCO3). K maintains corneal thickness; HCO3 supports mucin adhesion, promotes recovery, and helps regulate pH." },
  { id: 16, question: "Describe autologous serum eye drops — properties, required testing, and drawbacks.", answer: "Biologically similar to human tears (nutrients, pH, vitamins, fibronectin, growth factors); used at 20–100% concentration for severe ocular surface disease; serology (HIV, hepatitis, syphilis) is required. Benefits: epithelial healing, proliferation/migration, inhibition of inflammatory cytokines, increased goblet cells/mucin. Drawbacks: must be refrigerated, blood-borne infection and bacterial contamination risk, expensive, limited availability." },
  { id: 17, question: "How are secretagogues classified?", answer: "Oral: cholinergic agonists (pilocarpine, carbachol, bethanechol) and mucolytics (bromhexine, ambroxol). Topical: P2Y2 receptor agonist (diquafosol). They also reduce ocular surface inflammation." },
  { id: 18, question: "Oral pilocarpine — indication, dose, side effects, contraindications; and topical pilocarpine?", answer: "Indication: xerostomia (radiation-induced) and Sjögren syndrome; 5 mg orally qid. Side effects: excessive sweating, N/V, headache. Contraindicated in COPD, severe kidney disease, and heart disease. Topical pilocarpine has NO secretagogue effect." },
  { id: 19, question: "What is the mechanism and onset of diquafosol?", answer: "A P2Y2 purinergic receptor agonist that stimulates both water and mucin secretion; it takes about 2–4 weeks to see an effect (dosed roughly 6 times/day)." },
  { id: 20, question: "How does rebamipide work?", answer: "It promotes production of mucin-like glycoproteins (MUC1, MUC4, MUC16). Given as 2% QID; approved in Japan." },
  { id: 21, question: "Compare the mechanisms of cyclosporine A and lifitegrast in dry eye.", answer: "Cyclosporine A inhibits IL-2–driven T-lymphocyte activation (a calcineurin inhibitor), formulated as an oil-based emulsion (0.05% bid / 0.1% OD). Lifitegrast (5% bid) blocks the LFA-1/ICAM-1 interaction to inhibit T-cell migration (ICAM-1 is overexpressed on cornea/conjunctiva in dry eye)." },
  { id: 22, question: "How is doxycycline used in MGD, and what is its dual mechanism?", answer: "Doxycycline 100 mg bid for 1–2 weeks, then taper to 50 mg daily. Antibacterial effect decreases bacterial lipolytic enzymes; anti-inflammatory effect inhibits collagenase, phospholipase A2, and MMPs. Side effects: GI upset, photosensitization, azotemia. Contraindicated in pregnancy, breastfeeding, and allergy." },
  { id: 23, question: "Classify ocular allergy by hypersensitivity type.", answer: "Type I (IgE-mediated mast cell degranulation): acute allergic conjunctivitis, seasonal (SAC) and perennial (PAC) allergic conjunctivitis. Type IV (T-cell–mediated, delayed): vernal (VKC) and atopic (AKC) keratoconjunctivitis." },
  { id: 24, question: "What are the roles of H1 and H2 receptors in the early allergic response?", answer: "H1: increases vascular permeability → itching, pain, tearing, redness, and edema. H2: vasodilation, cell proliferation, and mucous production." },
  { id: 25, question: "What is the mechanism of mast cell stabilizers, and its clinical implication?", answer: "They block calcium influx into mast cells, preventing degranulation. Onset is delayed (~2 weeks), so they are used for prevention rather than acute relief (e.g., lodoxamide, pemirolast, cromolyn)." },
  { id: 26, question: "How do corticosteroids act in the arachidonic acid pathway, and how does that differ from NSAIDs?", answer: "Steroids inhibit phospholipase A2, blocking release of arachidonic acid and thereby suppressing BOTH the cyclooxygenase (prostaglandins) and lipoxygenase (leukotrienes) pathways. NSAIDs inhibit only cyclooxygenase. Steroids have no effect on mast cell/histamine release, but are the most potent agents for severe ocular allergy (short course ~2 weeks, effective in acute and chronic disease)." },
  { id: 27, question: "Which topical steroids have LOW versus HIGH IOP-raising potential?", answer: "Low potential: fluorometholone (FML) and loteprednol (an ester/'soft' steroid). High potential: 0.1% dexamethasone raises IOP the most; 1% prednisolone acetate (Pred Forte) is a potent anti-inflammatory. Loteprednol and FML are preferred when prolonged use is needed." },
  { id: 28, question: "List the ocular and systemic side effects of corticosteroids.", answer: "Ocular: ocular hypertension/glaucoma, posterior subcapsular cataract (PSC), secondary infection, poor epithelial healing, corneal thinning, uveitis, ptosis, and ocular discomfort. Systemic: adrenal insufficiency, Cushing syndrome, peptic ulcer, osteoporosis, hypertension/diabetes, muscle weakness/atrophy, activation of infection, and delayed wound healing." },
];

const CORNEA_MEDS_MCQ: MCQ[] = [
  { id: 1, question: "TFOS DEWS III lists all of the following as etiological in dry eye EXCEPT:", options: ["Tear film instability", "Hyperosmolarity", "Elevated intraocular pressure", "Neurosensory abnormalities"], correct: 2, explanation: "The DEWS III definition names tear film instability, hyperosmolarity, ocular surface inflammation/damage, and neurosensory abnormalities — not IOP." },
  { id: 2, question: "Which is a Step 1 (baseline) intervention for dry eye?", options: ["Autologous serum eye drops", "Punctal occlusion", "Low-viscosity lubrication and lid hygiene", "Amniotic membrane transplant"], correct: 2, explanation: "Step 1 is education/lifestyle, stopping offending meds, low-viscosity lubrication, and lid hygiene/warm compresses. The others are later steps." },
  { id: 3, question: "The main drawback of high-viscosity artificial tears is:", options: ["Corneal toxicity", "Transient blurring and debris on the eyelids", "Raised intraocular pressure", "Pupillary dilation"], correct: 1, explanation: "Higher viscosity improves retention but transiently blurs vision and can leave debris on the lids." },
  { id: 4, question: "Which demulcent is noted for promoting corneal epithelial healing?", options: ["Polyvinyl alcohol", "Carboxymethylcellulose (CMC)", "Dextran 70", "Propylene glycol"], correct: 1, explanation: "CMC is a high-molecular-weight cellulose derivative that can promote epithelial healing." },
  { id: 5, question: "Cationic oil-in-water nanoemulsion tears improve retention because:", options: ["Negatively charged droplets bind the cornea", "Positively charged oil droplets are attracted to negatively charged surface mucin", "They increase tear osmolarity", "They lower tear pH"], correct: 1, explanation: "Electrostatic attraction between the positively charged oil nanodroplets and negatively charged ocular surface mucin improves spreading and retention." },
  { id: 6, question: "An ointment (emollient) tear is most appropriate:", options: ["As daytime first-line for mild dry eye", "At night or for exposure keratopathy", "Immediately before driving", "For daytime use in contact lens wearers"], correct: 1, explanation: "Ointments blur vision, so they are used at night, for severe dry eye, and for exposure keratopathy." },
  { id: 7, question: "Compared with 0.3% HPMC or 1.4% PVA, 0.2% hyaluronic acid has:", options: ["Shorter residence time", "Significantly longer ocular surface residence time", "Higher preservative content", "No mucoadhesive property"], correct: 1, explanation: "0.2% HA has significantly longer ocular surface residence time than 0.3% HPMC or 1.4% PVA." },
  { id: 8, question: "Normal tear film osmolarity is approximately:", options: ["150–200 mOsm/L", "296–308 mOsm/L", "400–450 mOsm/L", "500 mOsm/L"], correct: 1, explanation: "Normal tear osmolarity is 296–308 mOsm/L; dry eye produces hyperosmolarity." },
  { id: 9, question: "Osmoprotectants (e.g., trehalose, betaine, L-carnitine) act by:", options: ["Raising tear osmolarity", "Protecting cells from osmotic stress without disturbing metabolism", "Blocking histamine", "Constricting conjunctival vessels"], correct: 1, explanation: "Osmoprotectants balance osmotic pressure without disturbing cell metabolism, reducing apoptosis, inflammatory cytokines, and corneal staining." },
  { id: 10, question: "Which preservative is a detergent-type with high ocular surface toxicity?", options: ["Sodium perborate", "Stabilized oxychloro complex (Purite)", "Benzalkonium chloride (BAK)", "Genaqua"], correct: 2, explanation: "BAK is a detergent preservative with high ocular toxicity; sodium perborate and SOC/Purite are gentler oxidizing agents." },
  { id: 11, question: "Preserved eye drops should generally be limited to:", options: ["Once daily", "≤ 4 times per day", "Unlimited frequency", "Night-time use only"], correct: 1, explanation: "Preserved drops used >4×/day long-term cause preservative sensitivity/toxicity; ≤4×/day is advised, otherwise switch to preservative-free." },
  { id: 12, question: "Which electrolytes are considered most critical in artificial tears?", options: ["Na and Cl", "Ca and Mg", "K and HCO3", "Fe and Cu"], correct: 2, explanation: "K (maintains corneal thickness) and HCO3 (mucin adhesion, recovery, pH) are the most critical electrolytes in artificial tears." },
  { id: 13, question: "Before prescribing autologous serum eye drops, which is required?", options: ["IOP measurement only", "Serologic testing for HIV, hepatitis, and syphilis", "Corneal topography", "Genetic testing"], correct: 1, explanation: "Blood-derived products require serology (HIV, hepatitis, syphilis) before preparation." },
  { id: 14, question: "Which statement about topical pilocarpine is correct?", options: ["It is the most effective topical secretagogue", "It has no secretagogue effect", "It stimulates P2Y2 receptors", "It is first-line for MGD"], correct: 1, explanation: "Only oral cholinergic agonists act as secretagogues; topical pilocarpine has no secretagogue effect." },
  { id: 15, question: "Oral pilocarpine is contraindicated in:", options: ["Hypertension only", "COPD, severe kidney disease, and heart disease", "Diabetes mellitus", "Migraine"], correct: 1, explanation: "Cholinergic stimulation is dangerous in COPD, severe renal disease, and heart disease." },
  { id: 16, question: "Diquafosol relieves dry eye by:", options: ["Blocking IL-2", "Stimulating the P2Y2 receptor to increase water and mucin secretion", "Inhibiting MMPs", "Constricting conjunctival vessels"], correct: 1, explanation: "Diquafosol is a P2Y2 purinergic agonist increasing aqueous and mucin secretion (effect in ~2–4 weeks)." },
  { id: 17, question: "Rebamipide improves the tear film by:", options: ["Reducing goblet cells", "Promoting mucin-like glycoproteins (MUC1, MUC4, MUC16)", "Blocking H1 receptors", "Raising tear osmolarity"], correct: 1, explanation: "Rebamipide up-regulates mucin-like glycoproteins (MUC1/4/16), improving the mucin layer." },
  { id: 18, question: "Lifitegrast reduces ocular surface inflammation by:", options: ["Blocking the LFA-1/ICAM-1 interaction to inhibit T-cell migration", "Stabilizing mast cells", "Antagonizing H1 receptors", "Inhibiting cyclooxygenase"], correct: 0, explanation: "Lifitegrast binds LFA-1 and blocks LFA-1/ICAM-1 binding; ICAM-1 is overexpressed on the ocular surface in dry eye." },
  { id: 19, question: "Doxycycline benefits MGD partly because it:", options: ["Increases bacterial lipase activity", "Inhibits collagenase, phospholipase A2, and MMPs", "Stimulates tear secretion via P2Y2", "Constricts conjunctival vessels"], correct: 1, explanation: "Beyond its antibacterial effect (reducing lipolytic enzymes), doxycycline inhibits collagenase, phospholipase A2, and MMPs." },
  { id: 20, question: "Doxycycline for MGD is contraindicated in:", options: ["Elderly patients", "Pregnancy and breastfeeding", "Diabetics", "Contact lens wearers"], correct: 1, explanation: "Tetracyclines are contraindicated in pregnancy and breastfeeding (and drug allergy)." },
  { id: 21, question: "Seasonal and perennial allergic conjunctivitis are mediated by:", options: ["Type IV (T-cell) delayed hypersensitivity", "Type I (IgE-mediated) hypersensitivity", "Type II cytotoxic reaction", "Type III immune-complex reaction"], correct: 1, explanation: "SAC and PAC are Type I, IgE-mediated mast cell degranulation. VKC and AKC involve Type IV." },
  { id: 22, question: "Vernal and atopic keratoconjunctivitis primarily involve:", options: ["Type I IgE-mediated degranulation only", "Type IV T-cell–mediated delayed hypersensitivity", "Complement-mediated cell lysis", "Neutrophilic vasculitis"], correct: 1, explanation: "VKC and AKC are chronic, T-cell–mediated (Type IV) forms of ocular allergy." },
  { id: 23, question: "Histamine acting on H1 receptors in the eye causes:", options: ["Vasoconstriction", "Increased vascular permeability → itching, redness, tearing, edema", "Suppression of mucous production", "Pupillary constriction"], correct: 1, explanation: "H1 stimulation raises vascular permeability, producing itching, redness, tearing, and edema; H2 causes vasodilation and mucous production." },
  { id: 24, question: "A key limitation of topical antihistamine eye drops (levocabastine, emedastine) is:", options: ["Slow onset over weeks", "Short duration of action (~3–4 hours)", "Raised intraocular pressure", "They stabilize mast cells only"], correct: 1, explanation: "Topical antihistamines act fast but only last ~3–4 hours, so they are often combined with a vasoconstrictor." },
  { id: 25, question: "A common problem with topical vasoconstrictor (decongestant) eye drops is:", options: ["Rebound congestion with chronic use", "Delayed onset over weeks", "Mast cell stabilization", "Lowering of IOP"], correct: 0, explanation: "Adrenergic vasoconstrictors cause rebound congestion; cautions include cardiovascular disease and angle-closure glaucoma." },
  { id: 26, question: "Mast cell stabilizers are best used:", options: ["For immediate relief of acute itching", "For prevention, because onset is delayed ~2 weeks", "As monotherapy for anaphylaxis", "To constrict conjunctival vessels"], correct: 1, explanation: "They block calcium influx and prevent degranulation, but the delayed (~2-week) onset makes them prophylactic agents." },
  { id: 27, question: "Olopatadine and ketotifen are examples of:", options: ["Pure vasoconstrictors", "Dual-acting antihistamine / mast cell stabilizers", "Calcineurin inhibitors", "NSAIDs"], correct: 1, explanation: "These multiple-action agents block H1 and stabilize mast cells (and affect eosinophils), giving both fast and sustained relief." },
  { id: 28, question: "How do corticosteroids differ from NSAIDs in the arachidonic acid pathway?", options: ["Steroids block only cyclooxygenase", "Steroids inhibit phospholipase A2 (upstream), blocking both COX and lipoxygenase; NSAIDs block only COX", "NSAIDs block phospholipase A2", "Both block only lipoxygenase"], correct: 1, explanation: "Steroids act upstream at phospholipase A2, suppressing both prostaglandins and leukotrienes; NSAIDs inhibit only COX." },
  { id: 29, question: "Which topical steroid has the LOWEST tendency to raise intraocular pressure?", options: ["0.1% Dexamethasone", "1% Prednisolone acetate", "Loteprednol or fluorometholone", "They all raise IOP equally"], correct: 2, explanation: "Loteprednol and fluorometholone have low IOP-raising potential; 0.1% dexamethasone raises IOP the most." },
  { id: 30, question: "Topical cyclosporine and tacrolimus share which mechanism/class?", options: ["Antihistamines", "Calcineurin inhibitors that block T-cell activation and cytokine production", "Mast cell stabilizers", "Adrenergic agonists"], correct: 1, explanation: "Both are calcineurin inhibitors; tacrolimus (binds FK-binding protein) is roughly 100× more potent than cyclosporine (binds cyclophilin)." },
];

export const RECALL: Record<string, RecallQ[]> = {
  "cornea/cornea-mannis/part1": CORNEA_BASIC_RECALL,
  "cornea/cornea-mannis/part4": CORNEA_MEDS_RECALL,
  "retina/ryans-retina/part1": RETINA_VIRAL_RECALL,
  "retina/bcsc-retina/part1": BCSC_FFA_RECALL,
};

export const MCQS: Record<string, MCQ[]> = {
  "cornea/cornea-mannis/part1": CORNEA_BASIC_MCQ,
  "cornea/cornea-mannis/part4": CORNEA_MEDS_MCQ,
  "retina/ryans-retina/part1": RETINA_VIRAL_MCQ,
  "retina/bcsc-retina/part1": BCSC_FFA_MCQ,
};

export function getRecall(topicId: string, bookId: string, partId: string): RecallQ[] {
  return RECALL[`${topicId}/${bookId}/${partId}`] ?? [];
}

export function getMcqPool(topicId: string, bookId: string, partId: string): MCQ[] {
  return MCQS[`${topicId}/${bookId}/${partId}`] ?? [];
}

// All MCQs across every playable part/book of a topic, combined for an
// exam-style session. IDs are re-numbered so questions from different parts
// (which each start at id 1) stay unique for React keys and answer tracking.
export function getTopicMcqPool(topicId: string): MCQ[] {
  const prefix = `${topicId}/`;
  return Object.entries(MCQS)
    .filter(([key]) => key.startsWith(prefix))
    .flatMap(([, questions]) => questions)
    .map((q, i) => ({ ...q, id: i + 1 }));
}
